use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::manifest::ArtifactType;

/// Per-project lockfile (.claude/rune.lock).
/// Records the exact state of each synced item, enabling
/// reproducible installs and accurate drift detection.
#[derive(Debug, Deserialize, Serialize, Default)]
pub struct Lockfile {
    #[serde(default)]
    pub skills: BTreeMap<String, LockedSkill>,

    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub agents: BTreeMap<String, LockedSkill>,

    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub rules: BTreeMap<String, LockedSkill>,
}

/// A locked entry -- records what was installed.
/// Name kept as LockedSkill for serde backward compatibility.
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct LockedSkill {
    /// Which registry this was synced from.
    pub registry: String,
    /// Content hash at sync time. If local differs, item was modified.
    pub hash: String,
    /// Registry's item-specific commit at sync time.
    /// If registry commit differs, upstream was updated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub registry_commit: Option<String>,
    /// When this item was last synced.
    pub synced_at: String,
}

impl Lockfile {
    pub fn path(project_dir: &Path) -> PathBuf {
        project_dir.join(".claude").join("rune.lock")
    }

    pub fn load(project_dir: &Path) -> Result<Self> {
        let path = Self::path(project_dir);
        if !path.exists() {
            return Ok(Self::default());
        }
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {}", path.display()))?;
        let lockfile: Lockfile = toml::from_str(&content)
            .with_context(|| format!("Failed to parse {}", path.display()))?;
        Ok(lockfile)
    }

    pub fn save(&self, project_dir: &Path) -> Result<()> {
        let path = Self::path(project_dir);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let content = toml::to_string_pretty(self).context("Failed to serialize lockfile")?;
        let header = "# Generated by rune sync. Do not edit manually.\n\n";
        std::fs::write(&path, format!("{header}{content}"))
            .with_context(|| format!("Failed to write {}", path.display()))?;
        Ok(())
    }

    /// Get the section map for a given type (immutable).
    pub fn section(&self, artifact_type: ArtifactType) -> &BTreeMap<String, LockedSkill> {
        match artifact_type {
            ArtifactType::Skill => &self.skills,
            ArtifactType::Agent => &self.agents,
            ArtifactType::Rule => &self.rules,
        }
    }

    /// Get the section map for a given type (mutable).
    pub fn section_mut(
        &mut self,
        artifact_type: ArtifactType,
    ) -> &mut BTreeMap<String, LockedSkill> {
        match artifact_type {
            ArtifactType::Skill => &mut self.skills,
            ArtifactType::Agent => &mut self.agents,
            ArtifactType::Rule => &mut self.rules,
        }
    }

    /// Total count of locked entries across all types.
    pub fn total_count(&self) -> usize {
        self.skills.len() + self.agents.len() + self.rules.len()
    }
}
