use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Per-project lockfile (.claude/rune.lock).
/// Records the exact state of each skill after sync, enabling
/// reproducible installs and accurate drift detection.
#[derive(Debug, Deserialize, Serialize, Default)]
pub struct Lockfile {
    #[serde(default)]
    pub skills: BTreeMap<String, LockedSkill>,
}

/// A locked skill entry -- records what was installed.
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct LockedSkill {
    /// Which registry this was synced from.
    pub registry: String,
    /// Content hash at sync time. If local differs, skill was modified.
    pub hash: String,
    /// Registry's skill-specific commit at sync time.
    /// If registry commit differs, upstream was updated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub registry_commit: Option<String>,
    /// When this skill was last synced.
    pub synced_at: String,
}

impl Lockfile {
    pub fn path(project_dir: &Path) -> PathBuf {
        project_dir.join(".claude").join("rune.lock")
    }

    pub fn load(project_dir: &Path) -> Result<Self> {
        let path = Self::path(project_dir);
        if !path.exists() {
            return Ok(Self::default());
        }
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {}", path.display()))?;
        let lockfile: Lockfile = toml::from_str(&content)
            .with_context(|| format!("Failed to parse {}", path.display()))?;
        Ok(lockfile)
    }

    pub fn save(&self, project_dir: &Path) -> Result<()> {
        let path = Self::path(project_dir);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let content = toml::to_string_pretty(self)
            .context("Failed to serialize lockfile")?;
        let header = "# Generated by rune sync. Do not edit manually.\n\n";
        std::fs::write(&path, format!("{header}{content}"))
            .with_context(|| format!("Failed to write {}", path.display()))?;
        Ok(())
    }
}
